#-------------------------------
# General Site Settings
title: John Gabatin
logo: g-logo.svg # You can add own logo.
description: 


#-------------------------------
# Author Settings
author:
  name: John Gabatin
  image: 01.jpg
  say-hello: Hello, Iâ€™m <strong>John Gabatin</strong>
  bio: 


#-------------------------------
# Contact links
github: https://github.com/jgabatin
email: jmgabatin@ucdavis.edu
linkedin: https://linkedin.com/in/jgabatin


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
